"""add source metadata to document chunks

Revision ID: 03d4341e3123
Revises: b35e0cee5305
Create Date: 2026-10-08 22:19:14.840293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d4341e3123'
down_revision: Union[str, Sequence[str], None] = 'b35e0cee5305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('slide_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('start_time', sa.Double(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_time', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'end_time')
    op.drop_column('document_chunks', 'start_time')
    op.drop_column('document_chunks', 'slide_number')
    # ### end Alembic commands ###
